Add twig function for sso params
rdey/auth0-bundle pull request #1
Opened 2018-03-04 10:24 UTC by ricsam

2018-03-04 12:12 UTC, magnusnordlander requested changes

2018-03-04 12:12 UTC, magnusnordlander commented on Twig/Auth0Extension.php
> +        if ($this->csrfTokenManager && $this->generator) {
`$this->generator` is required in the constructor, and thus always not null.

2018-03-04 12:12 UTC, magnusnordlander commented on Twig/Auth0Extension.php
> +                'token' => $token,
This should probably be renamed `csrf_token`.

2018-03-04 12:12 UTC, magnusnordlander commented on SSOUrlGenerator.php
> +    public function getAuth0Domain()
Add a blank line between methods.

2018-03-04 15:43 UTC, ricsam commented
@magnusnordlander Thanks 🦀! Can you merge this if you think it is okey?

2018-03-05 09:34 UTC, magnusnordlander requested changes

2018-03-05 09:34 UTC, magnusnordlander commented on SSOUrlGenerator.php
> +
I don't think it makes sense for the URL generator to have these getters, so remove them...

2018-03-05 09:34 UTC, magnusnordlander commented on Twig/Auth0Extension.php
> +            $domain = $this->generator->getAuth0Domain();
... and add them as constructor arguments in the extension. You'll also need to add them to the service definition in Resouces/config/services.yml.

2018-03-05 10:51 UTC, magnusnordlander approved these changes

2018-03-05 10:51 UTC, merged